runtime: python27
threadsafe: true
api_version: 1
basic_scaling:
  max_instances: 100

libraries:
- name: pycrypto
  version: 'latest'
- name: ssl
  version: 2.7.11

handlers:
- url: /api/.*
  script: main.api

env_variables:
  ENDPOINTS_SERVICE_NAME: broad-alicia-dev.appspot.com
