runtime: python27
threadsafe: true
api_version: 1
basic_scaling:
  max_instances: 2

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?setuptools/script \(dev\).tmpl$

libraries:
- name: pycrypto
  version: 'latest'
- name: ssl
  version: 2.7.11

handlers:
- url: /api/.*
  script: main.api

env_variables:
  ENDPOINTS_SERVICE_NAME: broad-alicia-dev.appspot.com
